# Generated by Django 3.0.3 on 2020-10-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0002_auto_20201024_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='inputfood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=200)),
                ('namefood1', models.CharField(max_length=200)),
                ('namefood2', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='inputroom',
        ),
    ]
